# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('enable', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Actions',
                'verbose_name': 'Action',
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Recipients',
                'verbose_name': 'Recipient',
            },
        ),
        migrations.CreateModel(
            name='SMTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('host', models.CharField(max_length=254)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('ssl_port', models.IntegerField(blank=True, null=True)),
                ('login', models.CharField(max_length=254)),
                ('password', models.CharField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'SMTPs',
                'verbose_name': 'SMTP',
            },
        ),
        migrations.AddField(
            model_name='action',
            name='recipients',
            field=models.ManyToManyField(to='mailer.Recipient'),
        ),
        migrations.AddField(
            model_name='action',
            name='smtp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailer.SMTP'),
        ),
    ]
