# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0002_smtp_use_ssl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='recipients',
        ),
        migrations.RemoveField(
            model_name='action',
            name='smtp',
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.DeleteModel(
            name='Recipient',
        ),
        migrations.DeleteModel(
            name='SMTP',
        ),
    ]
