# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0002_remove_action_smtp'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='smtp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailer.SMTP'),
        ),
    ]
