# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='recipient',
            field=models.TextField(),
        ),
    ]
