# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0002_auto_20170423_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('enable', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('sender', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Actions',
                'verbose_name': 'Action',
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Recipients',
                'verbose_name': 'Recipient',
            },
        ),
        migrations.AddField(
            model_name='action',
            name='recipients',
            field=models.ManyToManyField(to='sender.Recipient'),
        ),
    ]
