# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0003_auto_20170425_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='last_update',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='recipient',
            old_name='last_update',
            new_name='updated',
        ),
        migrations.AlterField(
            model_name='action',
            name='sender',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
